name: Cron Hello World

on:
  schedule:
    - cron: '0 * * * *' # Executa a cada hora, no início da hora

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
